targets:
  $default:
    builders:
      slang_build_runner:
        options:
          base_locale: hr
          fallback_strategy: base_locale
          input_directory: assets/translations
          input_file_pattern: .i18n.json
          output_directory: lib/generated/i18n
          output_file_name: translations.g.dart
          output_format: single_file
          flutter_integration: true
          namespaces: true
          class_name: AppTranslations