// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZqEjaxBE8e10Kz92InwItfjIuYEnfRyE',
    appId: '1:51796373713:web:f29119969e1ec0b71015f0',
    messagingSenderId: '51796373713',
    projectId: 'radi-li',
    authDomain: 'radi-li.firebaseapp.com',
    storageBucket: 'radi-li.appspot.com',
    measurementId: 'G-HRT4PT7SL2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDKYwYSwZfFsS3faP83xLE_gXfjZg4mcs',
    appId: '1:51796373713:android:7174a4db7f25b9491015f0',
    messagingSenderId: '51796373713',
    projectId: 'radi-li',
    storageBucket: 'radi-li.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNCrw7JL-BYLp_yixPRb9ptUsloooWJ7o',
    appId: '1:51796373713:ios:4acc7a448f0044281015f0',
    messagingSenderId: '51796373713',
    projectId: 'radi-li',
    storageBucket: 'radi-li.appspot.com',
    iosClientId:
        '51796373713-5ntoolqhe469o92osko9u09fm9nedgsn.apps.googleusercontent.com',
    iosBundleId: 'com.zeromolecule.radili.radili',
  );
}
